name: Trigger auto deployment for doc-manager

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/doc-manager-AutoDeployTrigger-7bbdffaa-f559-45f2-8422-2abe12bab395.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RUSTROCKERVITEREACT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RUSTROCKERVITEREACT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RUSTROCKERVITEREACT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.RUSTROCKERVITEREACT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RUSTROCKERVITEREACT_REGISTRY_PASSWORD }}
          containerAppName: rust-rocker-vite-react
          resourceGroup: serverless
          imageToBuild: giuliohome/doc-manager:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_

      # ----------------------------------------
      # Login to Docker Hub to push extra tags
      # ----------------------------------------
      - name: Docker login
        run: |
          echo "${{ secrets.RUSTROCKERVITEREACT_REGISTRY_PASSWORD }}" | \
            docker login docker.io \
              -u "${{ secrets.RUSTROCKERVITEREACT_REGISTRY_USERNAME }}" \
              --password-stdin

      # ----------------------------------------
      # Tag and push latest + e2e
      # ----------------------------------------
      - name: Tag and push latest + e2e
        run: |
          docker pull giuliohome/doc-manager:${{ github.sha }}
          docker tag giuliohome/doc-manager:${{ github.sha }} giuliohome/doc-manager:latest
          docker tag giuliohome/doc-manager:${{ github.sha }} giuliohome/doc-manager:e2e
          docker push giuliohome/doc-manager:latest
          docker push giuliohome/doc-manager:e2e
